### ISSUE TITLE
Type of `targetClass` parameter in `getClassProperties()` method

### ISSUE THREAD

**Issue by azerum** [wivelsfield/class-properties#210]
`getClassProperties()` specifies its parameter type to be `{ new (): Record<string, any>; }`, that is, a class with parameterless constructor. 

This type seems to be too restrictive, since I can't pass a class with a constructor that has parameters:

<img width="918" alt="изображение" src="https://user-images.githubusercontent.com/60925680/205397905-6224d909-82c1-40b6-8e5b-bf08d41c0c07.png">

Looking at the source code, it doesn't seem that this restriction is necessary: the library code never tries to instantiate the class with `new` and never deals with its constructor parameters

Am I missing something, or `targetClass` type can be safely changed to `{ new(...args: any[]): Record<string, any>; }` to allow constructors with parameters?

P.S. I tried to run the code casting `Foo` to `any`, and everything works fine

**Comment by simon-a-j** [comment]
> Am I missing something, or `targetClass` type can be safely changed to `{ new(...args: any[]): Record<string, any>; }` to allow constructors with parameters?

Good point, I think you're right. I'll fix this when I have a moment (unless you'd like to submit a PR?)

**Comment by azerum** [comment]
I am quite busy since recently, so it would be nice if you fixed it
